### ISSUE TITLE
Toolchain doesn't include correct gcc_stm32fx.cmake file

### ISSUE THREAD

**Issue by satrapes** [ObKo/stm32-cmake#109]
Hello I am running
`cmake -DSTM32_CHIP=STM32F401xE -DCMAKE_TOOLCHAIN_FILE=../../cmake/gcc_stm32.cmake -DCMAKE_MODULE_PATH=../../cmake -DSTM32_FAMILY=F4 ..`
which runs successfully to completion but for one thing.
My output  plus a debug message before includeing gcc_stm32
`
-- No TOOLCHAIN_PREFIX specified, using default: /usr

-- No TARGET_TRIPLET specified, using default: arm-none-eabi
STM32_FAMILY_LOWER: f4
STM32_FAMILY_LOWER: f4
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/bin/arm-none-eabi-gcc
STM32_FAMILY_LOWER: f1
-- Check for working C compiler: /usr/bin/arm-none-eabi-gcc -- works
-- Detecting C compiler ABI info
STM32_FAMILY_LOWER: f1
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/arm-none-eabi-g++
STM32_FAMILY_LOWER: f1
-- Check for working CXX compiler: /usr/bin/arm-none-eabi-g++ -- works
-- Detecting CXX compiler ABI info
STM32_FAMILY_LOWER: f1
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/arm-none-eabi-gcc
-- STM32F401xE is 401xE device
-- No STM32Cube_DIR specified, using default: /opt/STM32Cube_FW_F4_V1.24.0
-- Found CMSIS: /opt/STM32Cube_FW_F4_V1.24.0/Drivers/CMSIS/Device/ST/STM32F4xx/Include;/opt/STM32Cube_FW_F4_V1.24.0/Drivers/CMSIS/Include  
-- Found STM32HAL: /opt/STM32Cube_FW_F4_V1.24.0/Drivers/STM32F4xx_HAL_Driver/Inc  
-- No linker script specified, generating default
-- STM32F401xE has 512KiB of flash memory and 96KiB of RAM
-- Configuring done
-- Generating done
-- Build files have been written to: /home/satrapes/workspace/stm32-cmake/stm32-clang/cmake_bin`
I don't understand why does it print the message multiple times and why it trashes the value.

**Comment by ObKo** [comment]
Closing due to https://github.com/ObKo/stm32-cmake/pull/117 being merged and made this issue outdated.
