### ISSUE TITLE
Make error 

### ISSUE THREAD

**Issue by karimelQs** [ObKo/stm32-cmake#116]
Hello, 

after following all steps, during making step (Linker) this error occured :

[  7%] Linking C executable stm32-blinky
/mnt/c/Users/Bibi/Desktop/gcc-arm-none-eabi-7-2018-q2-update/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: cannot open output file stm32-blinky: Is a directory
collect2: error: ld returned 1 exit status
CMakeFiles/stm32-blinky.dir/build.make:372: recipe for target 'stm32-blinky' failed

Do you have any idea what is the source of the problem ? 

Thanks

**Comment by Hish15** [comment]
Can you give your cmake flags?
Can you confirm that prior this error you see your files being built properly? (provide output too please)
