### ISSUE TITLE
wrong about undefined reference to `SystemInit'

### ISSUE THREAD

**Issue by lsy563193** [ObKo/stm32-cmake#12]
sorry for my bad english .I meet some problem when I build in CMakeFiles/stm32-template.
Could you tell me what is wrong in it

CMakeFiles/stm32-template.dir/usr/arm-none-eabi/share/cmsis/startup_stm32f10x_md_vl.s.obj: In function `LoopFillZerobss':
(.text.Reset_Handler+0x26): undefined reference to`SystemInit'
collect2: error: ld returned 1 exit status
make[2]: **\* [stm32-template] Error 1
make[1]: **\* [CMakeFiles/stm32-template.dir/all] Error 2
make: **\* [all] Error 2

**Comment by ObKo** [comment]
It seems that CMSIS was built incorrectly.
* Do you use new version of stm32-cmake? (I'm porting it to STM32CubeMX instead of StdPeriphLib during this week. Old code is resting in ```old-stdperiph``` branch)
* Is ```/usr/arm-none-eabi/lib``` dir contains libcmsis_*.a files?
* Show me output of ```make VERBOSE=1```
