### ISSUE TITLE
Question - Targets with different architectures

### ISSUE THREAD

**Issue by koija** [ObKo/stm32-cmake#120]
I want to run some unit tests for my application (STM32L476) on qemu that does not support my platform. 
Is it possible in the same cmake project to have different targets (test suite, libraries) that are configured for different platforms?
For example to configure my test suite for STM32F411 and my tests for STM32L476.

Thanks!

**Comment by Hish15** [comment]
Of course you can :)
In the moder-cmake branch (WIP), you have the following [an example](https://github.com/ObKo/stm32-cmake/blob/modern-cmake/examples/blinky/CMakeLists.txt).
This is doable on the master branch of course. The idea is to use target. You can then define as many as you want!
