### ISSUE TITLE
Using Continuous integration with ST HAL

### ISSUE THREAD

**Issue by Hish15** [ObKo/stm32-cmake#121]
STMicroelectronics  ([example F4](https://github.com/STMicroelectronics/STM32CubeF4)) has put all the HALs for the STM32 serires on github.
The branch modern-cmake has test built in. This is the way to go.
Setting github actions ( or such) to at least build a simple project with all HAL is just one little step ahead.

**Comment by ObKo** [comment]
Take a look: https://github.com/ObKo/stm32-cmake/actions
