### ISSUE TITLE
Have binary size as output of build

### ISSUE THREAD

**Issue by atsju** [ObKo/stm32-cmake#166]
In general all build IDE provide the binary size at the end.
It would be cool to add something like this code to the examples:

```
#always display the code size
ADD_CUSTOM_TARGET(do_always ALL COMMAND arm-none-eabi-size --format=berkeley "myBinary"
                                DEPENDS myBinary)
```

**Comment by ObKo** [comment]
That was implemented in first version of stm32-cmake and seems lost during rewrite for modern cmake.

Will add it using add_custom_target()
