### ISSUE TITLE
Unsupported series STM32L5 and STM32WB

### ISSUE THREAD

**Issue by atsju** [ObKo/stm32-cmake#168]
- [x] unsupported L5 - merged in #172
- [ ] unsupported WB

**Comment by ObKo** [comment]
I'd took a look at stm32wb during implementation of modern-cmake branch and it was look quite tricky to support, so I'd decided to skip it for future.

Problem here is same as in H7 family - non-homogeneous multicore. 
As I understood, for now, only CM4 core is used for user application in most cases, RF core usually runs ST"s firmware for BLE/ZigBee/Thread.

**Comment by atsju** [comment]
Yes it's exactly what I though, it could be managed like H7 family.
From what I discussed with ST most users will use ST library for the second core but user may still build their own if needed. So both cores should be supported. I did't have a deep look into this for the moment, only used (only a little) their examples.
