### ISSUE TITLE
Add the ability to set the FLASH_ORIGIN for the linker script

### ISSUE THREAD

**Issue by NoamYu** [ObKo/stm32-cmake#230]
Because in my program I used a bootloader, I would like to be able to compile the program that will be in a different place in memory (not start at the default 0x8000000 but at 0x8008000).

I can't change the value of flash origin in the function stm32_get_memory_info because I'm also compiling the bootloader, So at first I need it as 0x8000000 and then 0x8008000.

I would like to determine the flash origin with a target setting.

**Comment by atsju** [comment]
Hello, 
I think the best option here is to use your own custom linker script for when compiling the bootloader. This would solve your problem. 
The linker script automatically generated by stm32-cmake is meant to be used in most of the "default" use cases for easy and fast compilation. As soon as you need some custom memory spaces or adresses you need to link against your own linker script.
You can have a look at this example : https://github.com/ObKo/stm32-cmake/tree/master/examples/custom-linker-script

**Comment by NoamYu** [comment]
Make sense, Thanks for the quick answer.
