### ISSUE TITLE
Allow user to modify compiler flags in CMake Cache

### ISSUE THREAD

**Issue by krtkr** [ObKo/stm32-cmake#25]
Hi everyone!

Any reasons to make all compiler, linker etc. flags CACHE INTERNAL instead of CACHE STRING?

Well, if I would like to build my project using your stm32-cmake library with -mfloat-abi=hard instead of -mfloat-abi=softfp I have to modify gcc_stm32f4.cmake file, which is something unexpected for me. Maybe I did something stupid and missed correct way to modify the flags?

My guess your library should help users to get everything compiling but not forcing them to use only your flags. It would be pretty nice to have possibility to change flags and play around optimization options without modifying build scripts at the stm32-cmake.

Making there flags CACHE STRING instead of INTERNAL should make the day. What do you think?

**Comment by mgiaco** [comment]
any news here?

**Comment by mgiaco** [comment]
@ObKo Do you know any other way to change the flags?

**Comment by ObKo** [comment]
stm32-cmake rework in progress: https://github.com/ObKo/stm32-cmake/pull/117

It will fix that issue.
