### ISSUE TITLE
HAL drivers detection without knowing the list of expected drivers

### ISSUE THREAD

**Issue by atsju** [ObKo/stm32-cmake#268]
**Is your feature request related to a problem? Please describe.**
as shown in #255 update of HAL could lead to new modules that are not automatically managed by the repo. 
Moreover adding them could cause issues with older versions of HAL repos.

**Describe the solution you'd like**
HAL files should be discovered automatically and not depending on HAL_DRIVERS_XX HAL_LL_DRIVERS_XX HAL_EX_DRIVERS_XX

**Comment by Hish15** [comment]
I love the idea! This is 1) doable and 2) makes more sense!
If you are not already working on this @atsju I might give it a try :)

**Comment by atsju** [comment]
Hello there. I am the one opening the ticket my friend :)

**Comment by atsju** [comment]
Go ahead. I didn't start anything on this.
