### ISSUE TITLE
-DNDEBUG in Release modes flags is missing

### ISSUE THREAD

**Issue by krtkr** [ObKo/stm32-cmake#28]
Dear stm32-cmake community,
it seems that 'NDEBUG' definition is kind of 'standard' for CMake release mode compilation flags. Some projects rely on it. I had a minor problems cross-compiling my project for STM32, while I was expecting this flag in release modes. Though It's not a big deal, maybe it is reasonable to keep common CMake's way and add this definition to release mode compilation flags?
I know adding this flag back might cause problems for other stm32-cmake based projects, so this issue is debatable.

**Comment by ObKo** [comment]
stm32-cmake rework in progress: https://github.com/ObKo/stm32-cmake/pull/117

It will fix that issue.
