### ISSUE TITLE
Multiple definitions problem while linking objects

### ISSUE THREAD

**Issue by wdembinski** [ObKo/stm32-cmake#282]
Have you encountered _multiple definitions_ errors while creating that project? I'm learning CMake and trying to do something similar on my own but I can't understand how to properly link libraries/packages (e.g. HAL) so there will be only a single object file/symbols per entire project. What type of libraries they should be created?

**Comment by atsju** [comment]
Read this at least 10 times and try out https://cmake.org/cmake/help/latest/command/add_library.html

I really lack your project architecture but what I suppose is that you build something like 
```
    A
 /     \
B1     B2
 \     /
    C
```
Then when linking in A in get C though B1 and B2. There are many solutions but I do not know your architecture.
Maybe OBJECTS library could do. But "it depends".

Alow me to close as this is off topic. 
You might get more help here: https://discourse.cmake.org/
or here : https://www.reddit.com/r/cmake/
