### ISSUE TITLE
quotes in --sysroot breaks clangd

### ISSUE THREAD

**Issue by Logiase** [ObKo/stm32-cmake#311]
**Describe the bug**
set `--sysroot` in `utilities.cmake` breaks clangd.

**Sources to reproduce**
any exmaple.

**Steps to reproduce**
1. Copy and build an example
2. take a look at `compile_commands.json`, and you will see `--sysroot=\\\"/usr/arm-none-eabi\\\"`
3. run `clangd --check={any source}`, and there's an error means clangd cant find system headers, and check `interlnal (cc1) args` in output, the redundant quotes and slash breaks the path.

**Expected behavior**
clangd is a very common lsp server, it should works fine

**Screenshots**

quotes break paths in clangd:
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/37612226/213268536-0a4b2854-ad0d-4c5f-9503-64deb0c7c225.png">

> see `-isysroot "\"/usr/arm-none-eabi\""` and `-internal-isystem "\"/usr/arm-nonea-eabi\"/include"`

redundant quotes and slashs in `compile_commands.json`:
![redundant quotes and slashs](https://user-images.githubusercontent.com/37612226/213266699-82a1de47-875c-4fdc-aaca-bb0c326c36f4.png)

**Environment (please complete the following information):**
 - OS: ArchLinux
 - Compiler: arm-none-eabi-gcc 12.2.0
 - stm32-cmake: abea01902bead78d9a5dd2f7603937da121fcc2c (newest)
 - cmake: 3.25.1

 - HAL/cube/CMSIS: stm32cubeh7 v1.11.0

**Additional context**
This problem has no effected on compilation, but it cause most IDE or editors which use clangd as LSP server does not work.

For example, `math.h` not found.

Remove quotes in `utilities.cmake` can solve this problem, but it also affects spaces in sysroot path.

> while the stm32cube hal library has no space protection 

I think it should be mentioned somewhere and tell users how to make `clangd` work, or just remove the quotes.

**Comment by Hish15** [comment]
Hello,

Thanks for this detailed issue. I can confirm this is an issue right now, but the solution is actually already on PR #290.
I will try to merge this PR and solve your issue :) 

Cya

**Comment by Logiase** [comment]
> 

Hi

PR #290 can fix this issue, and correctly handles the spaces in sysroot paath.

with spaces:
<img width="261" alt="image" src="https://user-images.githubusercontent.com/37612226/213358269-4c3d2458-9372-40bc-9bc3-14e3fee072a9.png">

without spaces:
<img width="168" alt="image" src="https://user-images.githubusercontent.com/37612226/213358343-88dded95-1397-4934-9be6-5dfea1c02a2c.png">

**Comment by atsju** [comment]
closing as fixed in #290
