### ISSUE TITLE
we need integration of H5 family and C0 family

### ISSUE THREAD

**Issue by atsju** [ObKo/stm32-cmake#318]
https://github.com/STMicroelectronics/STM32CubeH5
https://github.com/STMicroelectronics/STM32CubeC0

**Comment by xanthio** [comment]
See PR #331 for STM32C0 MCU support

**Comment by xanthio** [comment]
@Hish15, thanks for the H5 support.

I guess the unit tests are not executed for these targets as CMakeLists have not been updated.

**Comment by atsju** [comment]
Seems they are executed. See https://github.com/ObKo/stm32-cmake/actions/runs/7377399007
and https://github.com/ObKo/stm32-cmake/blob/986aaf9ef07a76e3d34a3e6c3a83f834af259631/.github/workflows/cmake.yml#L14

**Comment by xanthio** [comment]
OK, I didn't notice that family is pre-defined by github workflow. 

Nevertheless, I recommend updating the `CMakeLists.txt` file in each subdirectory on `test`
```
if(NOT TEST_FAMILIES)
    set(TEST_FAMILIES C0 F0 F1 F2 F3 F4 F7 G0 G4 H5 H7 L0 L1 L4 L5 MP1 U5 WB WL)
endif()
```

**Comment by atsju** [comment]
then maybe, we could do something like
```cmake
set(TEST_FAMILIES L4 F4)
message(warning blabla missing blabla)
```
to avoid futur omission beeing a problem

**Comment by Hish15** [comment]
Yes we don't want to manage families as it's done for now on UT. #334
