### ISSUE TITLE
Set flash origin and size?

### ISSUE THREAD

**Issue by mgiaco** [ObKo/stm32-cmake#37]
Hello, 

What is the correct way to set the flash origin and size?

I tried to set the documented variables this way:

```cmake
SET(STM32_FLASH_ORIGIN "0x08007400" CACHE STRING "set flash origin")
SET(STM32_FLASH_SIZE "94K" CACHE STRING "set flash origin")
```

but i only get:

```linker
MEMORY
{
  FLASH (rx)      : ORIGIN = 0x08007400, LENGTH = 128K
  RAM (xrw)      : ORIGIN = 0x20000000, LENGTH = 20K
```

By the way is there a possibility to set a custom linker file which is splitted into multiple files? The GNU ARM eclipse plugin uses a 3 file combination for linker files (libs.ld, mem.ld, and sections.ld) I like this schema but it would be great if there is a way to set all this three files as a custom linker files with stm32-cmake.

many thanks

**Comment by ObKo** [comment]
There is function
`STM32_SET_FLASH_PARAMS(TARGET STM32_FLASH_SIZE STM32_RAM_SIZE STM32_CCRAM_SIZE STM32_MIN_STACK_SIZE STM32_MIN_HEAP_SIZE STM32_FLASH_ORIGIN STM32_RAM_ORIGIN STM32_CCRAM_ORIGIN)`

Example:
`STM32_SET_FLASH_PARAMS(<your target> "94K" "20K" "0" "0" "0x400" "0x400" "0x08007400" "0x20000000" "0x10000000")`
(Don't forget to set valid CCRAM values, if you're using it)

> By the way is there a possibility to set a custom linker file which is splitted into multiple files?

Yes, take a look on ChibiOS exampes:
`SET(STM32_LINKER_SCRIPT ${ChibiOS_LINKER_SCRIPT})`
You can set any script you want (in place of ${ChibiOS_LINKER_SCRIPT})
