### ISSUE TITLE
[FR] set CMAKE_MODULE_PATH automatically

### ISSUE THREAD

**Issue by ildar** [ObKo/stm32-cmake#40]
Using [CMAKE_CURRENT_LIST_FILE](https://cmake.org/cmake/help/v3.0/variable/CMAKE_CURRENT_LIST_FILE.html)

**Comment by ObKo** [comment]
Implemented in 1910bc584ebd9258761897ca397d0b550b93921d
Thanks for idea!

**Comment by ildar** [comment]
This is great! Still the README.md should be fixed - delete the line:
> To use the toolchain, you'll need to copy contents of the `cmake` folder
into cmake's modules path, or use the `CMAKE_MODULE_PATH` variable.
