### ISSUE TITLE
CMAKE_TRY_COMPILE_TARGET_TYPE is 3.6-ism of cmake

### ISSUE THREAD

**Issue by ildar** [ObKo/stm32-cmake#41]
Use of CMAKE_TRY_COMPILE_TARGET_TYPE is against the README which tells cmake >= 3.0 is required. The CMAKE_TRY_COMPILE_TARGET_TYPE appeared in [3.6](https://cmake.org/cmake/help/v3.6/release/3.6.html).
Also I don't like https://github.com/ObKo/stm32-cmake/commit/1910bc584ebd9258761897ca397d0b550b93921d making several (3) changes in one commit.

**Comment by renaudcerrato** [comment]
I had to manually install cmake 3.7.2 on my distribution, but I agree that  CMAKE_TRY_COMPILE_TARGET_TYPE is cleaner than forcing compiler.

**Comment by ObKo** [comment]
Fixed in d33a0eaf0a0dcb05685a1927e77eb9e1bf9a34b8
