### ISSUE TITLE
Deprecated flags and errors

### ISSUE THREAD

**Issue by EnochTheWise** [ObKo/stm32-cmake#44]
Building example:
`cmake -DSTM32_CHIP=STM32F103C8 -DCMAKE_TOOLCHAIN_FILE=/home/john/work/stm32-cmake/stm32-cmake/cmake/gcc_stm32f1.cmake -DCMAKE_BUILD_TYPE=Release /home/john/work/stm32-cmake/stm32-cmake/stm32-blinky/`

CMakeError.log:
[CMakeError.txt](https://github.com/ObKo/stm32-cmake/files/912604/CMakeError.txt)

**Comment by ildar** [comment]
You supposed to use cross compiler. CMake tries your native compiler for
some reason. Check that.
