### ISSUE TITLE
Using EXECUTABLE_OUTPUT_PATH vs CMAKE_RUNTIME_OUTPUT_DIRECTORY

### ISSUE THREAD

**Issue by dacodas** [ObKo/stm32-cmake#45]
I noticed when configuring a project that gcc_stm32.cmake uses EXECUTABLE_OUTPUT_PATH rather than CMAKE_RUNTIME_OUTPUT_DIRECTORY when figuring out where to put the .elf, .hex, and .bin files. I was wondering if there's a big reason behind that (maintaining compatibility with older versions of CMake for example). I tried looking back and figuring out when exactly it was deprecated (at least since 3.0.2 it seems). 

Not sure how trivial a thing it is to change or if there is good reason for keeping it as such. 

Thanks!

**Comment by ObKo** [comment]
Closing due to https://github.com/ObKo/stm32-cmake/pull/117 being merged and made this issue outdated.
