### ISSUE TITLE
cmake build error

### ISSUE THREAD

**Issue by iZhangHui** [ObKo/stm32-cmake#46]
Hi @ObKo 

When I try to generate package of CMSIS and StdPeriph libraries and headers, cmake output error message as blelow. The step is following [package README.md](https://github.com/ObKo/stm32-cmake/tree/master/packages)

inflating: STM32F10x_StdPeriph_Lib_V3.5.0/_htmresc/CMSIS_Logo_Final.jpg  
  inflating: STM32F10x_StdPeriph_Lib_V3.5.0/_htmresc/logo.bmp  
CMake Error at CMakeLists.txt:52 (add_subdirectory):
  add_subdirectory given source "../cmsis" which is not an existing
  directory.

CMake Error at CMakeLists.txt:55 (get_property):
  get_property DIRECTORY scope provided but requested directory was not
  found.  This could be because the directory argument was invalid or, it is
  valid but has not been processed yet.

CMake Error at CMakeLists.txt:56 (add_subdirectory):
  add_subdirectory given source "../stdperiph" which is not an existing
  directory.

-- Configuring incomplete, errors occurred!

**Comment by ObKo** [comment]
Sorry, but package building is deeply outdated. In fact, it was added by some PR years ago and was actual only in early days of project. Now I'm going to take look at packaging and either update it or remove it completly.
