### ISSUE TITLE
generated linker for stm32f303 causes hard faults

### ISSUE THREAD

**Issue by bartslinger** [ObKo/stm32-cmake#54]
I experienced hard faults with the generated linker for my STM32F3 Discovery board. After a long puzzle, I used a linker file from the CMSIS directory:

`SET(STM32_LINKER_SCRIPT /home/bart/STM32Cube/Repository/STM32Cube_FW_F3_V1.6.0/Projects/STM32F3-Discovery/Examples/GPIO/GPIO_EXTI/SW4STM32/STM32F3-Discovery/STM32F303VCTx_FLASH.ld)`

The code is now running. The difference is a CCRAM specification:

in the memory section:
`CCMRAM (rw)      : ORIGIN = 0x10000000, LENGTH = 8K`

and further down after .data and before .bss:
```
 _siccmram = LOADADDR(.ccmram);

  /* CCM-RAM section 
  * 
  * IMPORTANT NOTE! 
  * If initialized variables will be placed in this section,
  * the startup code needs to be modified to copy the init-values.  
  */
  .ccmram :
  {
    . = ALIGN(4);
    _sccmram = .;       /* create a global symbol at ccmram start */
    *(.ccmram)
    *(.ccmram*)
    
    . = ALIGN(4);
    _eccmram = .;       /* create a global symbol at ccmram end */
  } >CCMRAM AT> FLASH

```

**Comment by ObKo** [comment]
Thanks for reporting. Quite nasty bug indeed.
