### ISSUE TITLE
Misaligned stack disables proper usage of printf with float variables on newlib.

### ISSUE THREAD

**Issue by PhSc** [ObKo/stm32-cmake#72]
The newlib-nano only works properly with an 8-byte aligned stack.

**Comment by Hish15** [comment]
This is solved in current master 
https://github.com/ObKo/stm32-cmake/blob/aad75627d39f51753e00ffc9add0f03f95d2a211/cmake/stm32/linker_ld.cmake#L122
https://github.com/ObKo/stm32-cmake/blob/aad75627d39f51753e00ffc9add0f03f95d2a211/cmake/stm32/linker_ld.cmake#L124

@ObKo you can close this issue 😄
