### ISSUE TITLE
question, package generation

### ISSUE THREAD

**Issue by denisacostaq** [ObKo/stm32-cmake#77]
I am having an error, if I go to https://github.com/ObKo/stm32-cmake/tree/master/packages and I try to run:

```
mkdir packages/build
cd packages/build
cmake .. -DSTM32_FAMILY=F4
```

My error:

.
.
.
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/arm-none-eabi-gcc
CMake Error at /opt/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CMSIS (missing: CMSIS_INCLUDE_DIRS CMSIS_SOURCES)
Call Stack (most recent call first):
  /opt/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/adacosta/Rusia/stm32-cmake/cmake/FindCMSIS.cmake:152 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:8 (FIND_PACKAGE)
.
.
.

What should CMake find this?

https://github.com/ObKo/stm32-cmake/blob/master/packages/CMakeLists.txt#L52

**Comment by ObKo** [comment]
Closing due to https://github.com/ObKo/stm32-cmake/pull/117 being merged and made this issue outdated.
