### ISSUE TITLE
GCC Link time optimization makes it impossible to override interrupt handlers

### ISSUE THREAD

**Issue by t123yh** [ObKo/stm32-cmake#78]
Steps to reproduce:
* Create a project named Project.
* Write an interrupt handler, such as 
```c
void HardFault_Handler(void)
{
    while (1)
    {
    }
}
```

* Build the project in DEBUG mode.
* Run `nm Project | grep Handler` and find the handler you've just written. You can see it's in a different address than most handlers, which shows that it's overriden by our custom handler.
* Now build the project in RELEASE mode.
* Run `nm Project | grep Handler` again. This time you should see that your handler is the same as other handlers, which means that it's not overriden.
* Remove `-flto` in gcc_stm32.cmake line 74-77 and build again. You can see that the handler comes back.

This indicates that the GCC link time optimization has removed our handlers. That's why my SysTick_Handler not working and the RTOS can't get SysTick signal and stuck there.

There are two temporary workarounds: 
* Remove the weak definitions of the handlers you want to override in `STM32Cube_FW_F0_V1.9.0/Drivers/CMSIS/Device/ST/STM32F0xx/Source/Templates/gcc/startup_stm32f031x6.s`(modify the path to suit your MCU)
```diff
-  .weak      HardFault_Handler
-  .thumb_set HardFault_Handler,Default_Handler
```

* Or disable `-flto` option as described above.

Hope someone could solve this problem.

**Comment by Windoze345** [comment]
This is a bug in the arm-gcc compiler (see: https://bugs.launchpad.net/gcc-arm-embedded/+bug/1747966 )
You can also work around it by changing the order of the sources in your cmake-file.
The System Headers / Sources need to be before your own code:
ADD_EXECUTABLE(Project ${CMSIS_SOURCES} main.c)
