### ISSUE TITLE
Adding OpenCV to project

### ISSUE THREAD

**Issue by M-Mehranian** [ObKo/stm32-cmake#80]
I have an image processing project and I use OpenCV library on PC. Now I must to implement it on an ARM micro like stm32f4 series(They have not OS). How can I build OpenCV for stm32 micros? (The problem is OpenCV is written in C++ but we must write in C language in order to program the code)

**Comment by szechyjs** [comment]
There is nothing that prevents you from using C++ on a arm micro. It all gets compiled to the same machine code.
