### ISSUE TITLE
Automatically create * .bin * .hex

### ISSUE THREAD

**Issue by darkprof83** [ObKo/stm32-cmake#88]
Use this in gcc_stm32.cmake
`
ADD_CUSTOM_TARGET(${TARGET}.hex ALL DEPENDS ${TARGET} COMMAND ${CMAKE_OBJCOPY} -Oihex ${FILENAME} ${FILENAME}.hex)
`

**Comment by thopiekar** [comment]
I find it useful to have this functionality. Many buildsystems are doing this and it doesn't take much time to generate these files.
@darkprof83 How about making a PR about it (if not already done)? In case people agree with us, we might be able to get it with a minimum of effort for @ObKo :wink:

**Comment by darkprof83** [comment]
My PR https://github.com/ObKo/stm32-cmake/pull/125
