### ISSUE TITLE
Don't Assume BSP Components Have Source Files

### ISSUE THREAD

**Issue by I-AM-EXFOLIATING** [ObKo/stm32-cmake#89]
FindSTM32BSP.cmake wrongly assumes that all the components of the STM32Cube board support packages contain a source file. This is generally true but does not apply to the LCD module components and a serial flash component (ampire480272, ampire640480, and n25q256a), which contain headers only (STM32Cube v1.23.0).

If one includes a line like `find_package(STM32BSP COMPONENTS ampire480272 ampire640480 n25q256a REQUIRED)` in their `CMakeLists.txt` in addition to `add_executable(${CMAKE_PROJECT_NAME} ${STM32BSP_SOURCES}` then FindSTM32BSP.cmake will attempt to locate the source for these components and give output like below
```
-- BSP file is BSP_ampire480272.c_FILE-NOTFOUND
-- BSP file is BSP_ampire640480.c_FILE-NOTFOUND
-- BSP file is BSP_n25q256a.c_FILE-NOTFOUND
```
FindSTM32BSP:50 blindly appends the non-existent source file to `BSP_SRC` which is later used in the project as `${STM32BSP_SOURCES}`, giving output
```
CMake Error at CMakeLists.txt:41 (add_executable):
  Cannot find source file:

    BSP_ampire480272.c_FILE-NOTFOUND

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
```

A temporary workaround for this issue is to create some empty source files in the STM32Cube BSP source tree.

**Comment by ObKo** [comment]
Closing due to https://github.com/ObKo/stm32-cmake/pull/117 being merged and made this issue outdated.
