### ISSUE TITLE
Add support for STM32H7 family

### ISSUE THREAD

**Issue by Hish15** [ObKo/stm32-cmake#90]
Check out [this monster](https://www.youtube.com/watch?v=LAx2iqlu9ts), we have to have it :).

The STM32F7 is already handled so I think there is not much work to do.
If I'm not wrong it's just the cmake/gcc_stm32H7.cmake to write right?

Edit : I've done it and will PR it later this week :)

**Comment by liarokapisv** [comment]
Hello @Hish15 , I am also interested in support for this family. Did you ever get to that PR?

**Comment by Hish15** [comment]
Hi,
I did work here :
https://github.com/Hish15/stm32-cmake/tree/HandlingH7Family  but no PR.I
droped the idea to use it and made it work on my own from scratch.
I wanted to learn :)
it took a lot of time but it's not hard at all!

I wiil try to make the PR actually :)

Greetings

**Comment by Hish15** [comment]
closed by #104
