### ISSUE TITLE
Board support packages for more Nucleo / Discovery boards

### ISSUE THREAD

**Issue by I-AM-EXFOLIATING** [ObKo/stm32-cmake#93]
It seems to me that board support packages are not directly supported except for `STM32F429I-Discovery`, since stm32-cmake will only set the variables `BSP_HEADERS` and `BSP_SRC` in FindSTM32BSP.cmake, if `STM_BOARD` is `STM32F429I-Discovery`.

The user can work around this by manually pointing these two variables to the appropriate files for their target development board, for example:
```
set(BSP_HEADERS "stm32f4xx_nucleo_144.h")
set(BSP_SRC "stm32f4xx_nucleo_144.c")
find_package(STM32BSP REQUIRED)
```

**Comment by ObKo** [comment]
Closing due to https://github.com/ObKo/stm32-cmake/pull/117 being merged and made this issue outdated.
