### ISSUE TITLE
Generated linker file wastes 4 bytes of stack

### ISSUE THREAD

**Issue by glinders** [ObKo/stm32-cmake#94]
The following line in file stm32_linker.cmake initialises the reset stack pointer to an odd address:

      "_estack = ${STM32_RAM_ORIGIN} + ${STM32_RAM_SIZE} - 1\;\n"

For instance, on an STM32F070 (16kB or SRAM) this results in the address 0x20003fff. 

When the stack pointer on an STM32 MCU is loaded, bits 0 and 1 are always set to zero, resulting in address 0x20003ffc. When the stack is used, the stack pointer is first decremented before data is placed on the stack. That means that the top 4 bytes of the stack are never used.

This can easily be fixed by changing the line to:

      "_estack = ${STM32_RAM_ORIGIN} + ${STM32_RAM_SIZE}\;\n"

**Comment by Hish15** [comment]
Good catch.
To rephrase the issue `_estack` has to be 4bytes aligned
This is solved in current master 
https://github.com/ObKo/stm32-cmake/blob/aad75627d39f51753e00ffc9add0f03f95d2a211/cmake/stm32/linker_ld.cmake#L23

@ObKo, you can close this issue
