### ISSUE TITLE
automatic discovery of components

### ISSUE THREAD

**Issue by maciejmatuszak** [ObKo/stm32-cmake#96]
I am trying to use the stm32-cmake package in my project but I come across new extended component in F7 firmware. The available HAL components and extended components are hard-coded in cmake/FindSTM32HAL.cmake. Instead of just adding the missing entry I created cmake function that scans the available files and discovers components automatically and override the hand crafted lists. this functionality is enabled via cmake flag. Check this branch: https://github.com/maciejmatuszak/stm32-cmake/tree/automatic_component_discovery
I also added macro to enable the components by creating target defines HAL_XXX_MODULE_ENABLED this can replace the modification of the stm32fXxx_hal_conf.h file. The list of component you want to use can be set into variable:

```cmake
set(REQUIRED_COMPONENTS uart tim spi adc dac gpio rtc dma exti rcc flash pwr i2c cortex)
```
and then reused:
```cmake
FIND_PACKAGE(STM32HAL COMPONENTS ${REQUIRED_COMPONENTS} REQUIRED)
...
...
STM32_ENABLE_HAL_COMPONENT(${CMAKE_PROJECT_NAME} ${REQUIRED_COMPONENTS})
```

I would suggest to include this functionality back to this repo.

**Comment by mgiaco** [comment]
Why not add a pull?
